services:
  - type: web
    name: rag-pipeline-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: FRONTEND_URL
        sync: false
    healthCheckPath: /docs
    autoDeploy: true
